export const NavigationKeys = {
	SplashScreen: 'SplashScreen',
	IntroScreen: 'IntroScreen',
	LocationPermission: 'LocationPermission',
	AuthNavigator: 'AuthNavigator',
	BottomTab: 'BottomTab',
	HomeScreen: 'HomeScreen',
	SettingScreen: 'SettingScreen',
	SigninScreen: 'SigninScreen',
	SignupScreen: 'SignupScreen',
	ForgotPasswordScreen: 'ForgotPasswordScreen',
	ResetPasswordScreen: 'ResetPasswordScreen',
	OtpScreen: 'OtpScreen',
	AddMobileNumber: 'AddMobileNumber',
	FinalUser: 'FinalUser',
	DetailScreen: 'DetailScreen',
	StarterScreen: 'StarterScreen',

	DriverInformation: 'DriverInformation',
	AddCarDetails: 'AddCarDetails',
	AddPayments: 'AddPayments',

	AddEmergencyContacts: 'AddEmergencyContacts',
	NextOfKin: 'NextOfKin',
	AddDocuments: 'AddDocuments',
};
