export const passengerListing = [
	{
		name: 'John Doe',
		company: 'Flex',
		price: '€50',
		distance: '5km away',
		time: '10:15am',
		from: 'Berlin',
		to: 'Munich',
		image: 'https://randomuser.me/api/portraits/men/13.jpg',
	},
	{
		name: 'Jane Smith',
		company: 'Flex',
		price: '€45',
		distance: '10km away',
		time: '11:30am',
		from: 'Hamburg',
		to: 'Frankfurt',
		image: 'https://randomuser.me/api/portraits/women/14.jpg',
	},
	{
		name: 'Mark Lee',
		company: 'Flex',
		price: '€60',
		distance: '7km away',
		time: '12:00pm',
		from: 'Cologne',
		to: 'Stuttgart',
		image: 'https://randomuser.me/api/portraits/men/15.jpg',
	},
	{
		name: 'Anna Becker',
		company: 'Flex',
		price: '€55',
		distance: '3km away',
		time: '9:45am',
		from: 'Berlin',
		to: 'Hamburg',
		image: 'https://randomuser.me/api/portraits/women/16.jpg',
	},
	{
		name: 'Luke Brown',
		company: 'Flex',
		price: '€40',
		distance: '8km away',
		time: '2:30pm',
		from: 'Munich',
		to: 'Nuremberg',
		image: 'https://randomuser.me/api/portraits/men/17.jpg',
	},
	{
		name: 'Sarah White',
		company: 'Flex',
		price: '€65',
		distance: '15km away',
		time: '1:00pm',
		from: 'Düsseldorf',
		to: 'Leipzig',
		image: 'https://randomuser.me/api/portraits/women/18.jpg',
	},
	{
		name: 'Michael Green',
		company: 'Flex',
		price: '€55',
		distance: '12km away',
		time: '3:45pm',
		from: 'Hamburg',
		to: 'Frankfurt',
		image: 'https://randomuser.me/api/portraits/men/19.jpg',
	},
	{
		name: 'Sophie Black',
		company: 'Flex',
		price: '€45',
		distance: '6km away',
		time: '8:30am',
		from: 'Cologne',
		to: 'Stuttgart',
		image: 'https://randomuser.me/api/portraits/women/12.jpg',
	},
	{
		name: 'Chris Gray',
		company: 'Flex',
		price: '€50',
		distance: '5km away',
		time: '4:00pm',
		from: 'Berlin',
		to: 'Munich',
		image: 'https://randomuser.me/api/portraits/men/21.jpg',
	},
	{
		name: 'Tina Wright',
		company: 'Flex',
		price: '€70',
		distance: '20km away',
		time: '12:30pm',
		from: 'Frankfurt',
		to: 'Nuremberg',
		image: 'https://randomuser.me/api/portraits/women/22.jpg',
	},
	{
		name: 'David Harris',
		company: 'Flex',
		price: '€60',
		distance: '7km away',
		time: '10:00am',
		from: 'Stuttgart',
		to: 'Cologne',
		image: 'https://randomuser.me/api/portraits/men/23.jpg',
	},
	{
		name: 'Emma King',
		company: 'Flex',
		price: '€50',
		distance: '4km away',
		time: '1:30pm',
		from: 'Berlin',
		to: 'Frankfurt',
		image: 'https://randomuser.me/api/portraits/women/24.jpg',
	},
	{
		name: 'Tom Adams',
		company: 'Flex',
		price: '€40',
		distance: '9km away',
		time: '6:00pm',
		from: 'Munich',
		to: 'Hamburg',
		image: 'https://randomuser.me/api/portraits/men/25.jpg',
	},
	{
		name: 'Lisa Scott',
		company: 'Flex',
		price: '€35',
		distance: '6km away',
		time: '7:00am',
		from: 'Nuremberg',
		to: 'Leipzig',
		image: 'https://randomuser.me/api/portraits/women/26.jpg',
	},
	{
		name: 'Jack Lewis',
		company: 'Flex',
		price: '€60',
		distance: '13km away',
		time: '2:15pm',
		from: 'Berlin',
		to: 'Düsseldorf',
		image: 'https://randomuser.me/api/portraits/men/27.jpg',
	},
	{
		name: 'Olivia Martin',
		company: 'Flex',
		price: '€50',
		distance: '5km away',
		time: '9:00am',
		from: 'Frankfurt',
		to: 'Cologne',
		image: 'https://randomuser.me/api/portraits/women/28.jpg',
	},
	{
		name: 'Ben Walker',
		company: 'Flex',
		price: '€45',
		distance: '7km away',
		time: '3:30pm',
		from: 'Hamburg',
		to: 'Nuremberg',
		image: 'https://randomuser.me/api/portraits/men/29.jpg',
	},
	{
		name: 'Sophia Thompson',
		company: 'Flex',
		price: '€55',
		distance: '8km away',
		time: '11:00am',
		from: 'Munich',
		to: 'Frankfurt',
		image: 'https://randomuser.me/api/portraits/women/30.jpg',
	},
	{
		name: 'James Clark',
		company: 'Flex',
		price: '€50',
		distance: '9km away',
		time: '5:00pm',
		from: 'Stuttgart',
		to: 'Berlin',
		image: 'https://randomuser.me/api/portraits/men/32.jpg',
	},
];
